name: generate github stats cards

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

  # run on every push on the main branch
  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate stats.svg
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&hide_border=true
          path: dist/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: generate stats-dark.svg
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&hide_border=true&theme=github_dark
          path: dist/stats-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: generate top-langs.svg
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&hide_border=true
          path: dist/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: generate top-langs-dark.svg
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&hide_border=true&theme=github_dark
          path: dist/top-langs-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # the branch is overwritten on every run, so it must not be shared with other workflows
      - name: push cards to the output-stats branch
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output-stats
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
